#!/bin/bash

set -euo pipefail

# given a file (or directory) as an argument, will update the current DB

readonly F=$(mktemp)

if [ -d "$1" ]
then
    # changed this from `cat "$1"/* | ...` when the directories got too big
    find "$1" -maxdepth 1 -type f -print0 | xargs -0 -n 1023 cat | grep -h SUCCESS | ../strip > "$F"
elif [ -f "$1" ]
then
    grep SUCCESS "$1" | ../strip > "$F"
else
    echo "$1 is not a file or directory; exiting!"
    exit 1
fi


for E in $(cat ENERGIES)
do
    for K in D A R
    do
	echo "$E" $K;
	awk "\$3==$E && \$2==\"$K\"" < "$F" >> "$E.$K.done"
	./uniqus "$E.$K.done"
    done
done

rm "$F"
